name: Run Tests on Merge

on:
  push:
    branches-ignore:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install dependencies (update with your project-specific requirements)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Python/requirements.txt

    # Install the package to be tested
    - name: Install HAT
      run: |
        cd Python
        pip install -e .
        cd ..

    # Run the test cases
    - name: Run test cases
      run: |
        pytest ./Tests/run_tests.py
